# Generated by Django 4.0.5 on 2022-07-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('creator', models.CharField(blank=True, max_length=200, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'News Articles',
            },
        ),
        migrations.CreateModel(
            name='Rss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'RSS Urls',
            },
        ),
    ]
