# Generated by Django 4.0.5 on 2022-07-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News Articles'},
        ),
        migrations.AlterModelOptions(
            name='rss',
            options={'verbose_name_plural': 'RSS Urls'},
        ),
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
